const MAIN_PAGE = 'slackv2';
const MESSAGES_MAX_COUNT = 100;
const OPEN = 1;
const HIDE_HEADER_TIME_INTERVAL_IN_SECONDS = (process.env.HEADER_HIDE_TIME_INTERVAL_IN_MIN || 5) * 60;

module.exports = {
  OPEN,
  MAIN_PAGE,
  MESSAGES_MAX_COUNT,
  HIDE_HEADER_TIME_INTERVAL_IN_SECONDS
};
